steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/hello-world-cron-job:latest', '.']
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/${PROJECT_ID}/hello-world-cron-job:latest']
options:
  logging: CLOUD_LOGGING_ONLY
