apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-world-cron-job
spec:
  schedule: "* * * * *" # This schedule runs the job every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-world-cron-job
            image: hello-world-cron-job:latest
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
